# Generated by Django 5.1.2 on 2024-10-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('turma', '0002_alter_turma_options_remove_turma_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_da_turma', to='turma.turma'),
        ),
    ]
