# Generated by Django 5.1.2 on 2024-10-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_turma'),
        ('turma', '0003_turma_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.AddField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(related_name='alunos_turmas', to='turma.turma'),
        ),
    ]
