# Generated by Django 5.1.2 on 2024-10-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_remove_aluno_turma_aluno_turmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='colocacao_geral',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.BooleanField(default=False),
        ),
    ]
