# Generated by Django 5.1.2 on 2024-10-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_aluno_colocacao_geral_alter_aluno_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='user',
        ),
        migrations.AddField(
            model_name='aluno',
            name='email_responsavel',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='Email do Responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(default='Nome Padrão', max_length=100, verbose_name='Nome do Aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_responsavel',
            field=models.CharField(default='Nome do Responsável', max_length=100, verbose_name='Nome do Responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_responsavel',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Número do Responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='colocacao_geral',
            field=models.IntegerField(default=0, verbose_name='Colocação Geral'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.BooleanField(default=True, verbose_name='Matriculado'),
        ),
    ]
