# Generated by Django 5.1.3 on 2024-11-12 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_alter_aluno_email_responsavel_alter_aluno_nome_aluno_and_more'),
        ('simulado', '0003_alter_simulado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(verbose_name='Nota')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno', verbose_name='Aluno')),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.simulado', verbose_name='Simulado')),
            ],
        ),
    ]
