# Generated by Django 5.1.3 on 2024-11-12 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_resultadosimulado'),
        ('simulado', '0003_alter_simulado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosimulado',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='resultadosimulado',
            name='nota',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resultadosimulado',
            name='simulado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulado.simulado'),
        ),
    ]
