# Generated by Django 5.1.2 on 2024-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('horario', models.FloatField()),
                ('dias', models.CharField(max_length=100)),
            ],
        ),
    ]
