# Generated by Django 5.1.2 on 2024-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.RemoveField(
            model_name='turma',
            name='horario',
        ),
        migrations.AddField(
            model_name='turma',
            name='horario_fim',
            field=models.TimeField(default='07:00', verbose_name='Horário de Fim'),
        ),
        migrations.AddField(
            model_name='turma',
            name='horario_inicio',
            field=models.TimeField(default='06:00', verbose_name='Horário de Início'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Professor Responsável'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dias',
            field=models.CharField(max_length=100, verbose_name='Dias da Semana'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Turma'),
        ),
    ]
