# Generated by Django 5.1.2 on 2024-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_turma'),
        ('turma', '0002_alter_turma_options_remove_turma_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas_matriculadas', to='aluno.aluno'),
        ),
    ]
