# Generated by Django 5.1.2 on 2024-10-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_remove_aluno_turma_aluno_turmas'),
        ('turma', '0003_turma_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas_matriculadas', to='aluno.aluno', verbose_name='Alunos'),
        ),
    ]
