# Generated by Django 5.1.2 on 2024-10-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulado',
            name='materia',
            field=models.CharField(choices=[('portugues', 'Português'), ('matematica', 'Matemática')], default='portugues', max_length=20),
        ),
    ]
